### ISSUE TITLE
Challenge: Add ability to type guesses in physical keyboard

### ISSUE THREAD

**Issue by TheNunoGomes** [Ze1598/wordle-clone#1]
# One possible approach 

Event listener on the relevant container element to listen to key presses - https://www.w3schools.com/jsref/event_onkeypress.asp

**Comment by Ze1598** [comment]
Hi Nuno,
Thanks for the fun challenge. The functionality [has been implemented](https://github.com/Ze1598/wordle-clone/commit/60f43bf4e753a4193803dc03e070f842566f1f6f) by adding a keyDown event listener to the window element - so the user doesn't need to click anything for the game to recognise physical keyboard input.
